language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install:
  - python bootstrap.py
  - bin/buildout

#before_script:
#  - "pep8 --exclude=migrations --ignore=E501,E225 src"

script: bin/specs

notifications:
  email:
    - travis@oldhammade.net
